### ISSUE TITLE
README.md and bower.json versions don't match

### ISSUE THREAD

**Issue by yurydelendik** [joseym/pdfjs-bower#1]
Not sure if that matters much, but bower.json say version "0.0.1" and README.md refers to "v1.0.68". However https://github.com/joseym/pdfjs-bower/blob/master/dist/pdf.js#L24 says "1.0.180". None of those versions match to stable version of PDF.js (http://mozilla.github.io/pdf.js/getting_started/)

**Comment by joseym** [comment]
`0.0.1` refers to the bower package, but you are correct in the other.

I referred to [pdf.js/blob/master/pdfjs.config](https://github.com/mozilla/pdf.js/blob/master/pdfjs.config#L2) when getting the version number, but I guess `pdf.js` isn't building based on that config?

**Comment by yurydelendik** [comment]
Yep, it's done by person who is releasing the pdf.js version https://github.com/mozilla/pdf.js/pull/4585

**Comment by yurydelendik** [comment]
That's done because people decided that for QA is important to have a person, who will make a call about whether the version good as release or not.

**Comment by joseym** [comment]
I see.

I just created a new release for `v1.0.180` and matched bowers version to it, just to help with any confusion.
